{% set name = "htmx-flask" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/htmx_flask-{{ version }}.tar.gz
  sha256: 393defc4a5a20a006fc4a96254f6a3ee8522789e7d886d22a02486ecb9d176af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - flask >=2.1.0

test:
  imports:
    - htmx_flask
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sponsfreixes/htmx-flask
  summary: htmx support for Flask
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
